# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: hoverkraft-tech/compose-action@v2.2.0
      with: 
        compose-file: "${{ github.workspace }}/docker-compose.yml"
        down-flags: "--volumes"
        services:  |
         ea_api
         ea_webapp
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Wait for ea_webapp
      run: |
        for i in {1..30}; do
          if curl --silent http://localhost:5001 > /dev/null; then
            echo "ea_webapp is up!"
            break
          fi
          echo "Waiting for ea_webapp..."
          sleep 2
        done

    - name: Run headless tests
      uses: coactions/setup-xvfb@v1.0.1
      with: 
        working-directory: ./EaApplicationTest
        run: dotnet test --no-build --verbosity normal
      continue-on-error: false
 
           
